version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/tgrk/apidiff

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "vendor/vendor.json" }}

      - run:
          name: Fetch dependencies
          command: make deps && make ciDeps

      - run:
          name: Run linter
          command: make lint

      - run:
          name: Run unit tests
          command: |
            make ciTest | go-junit-report > /tmp/test-results/report.xml/report.xml

      - save_cache:
          key: pkg-cache-{{ checksum "vendor/vendor.json" }}
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

